"""empty message

Revision ID: d6f15ae33750
Revises: ec87ba35ceff
Create Date: 2020-07-17 10:43:27.748410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6f15ae33750'
down_revision = 'ec87ba35ceff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.Integer(), nullable=False))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['author'], ['_id'])
    op.drop_column('post', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'user', ['userId'], ['_id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###
